model:
  base_learning_rate: 1.0e-6
  target:  ldm.models.autoencoder.IVAE
  params:
    monitor: "val/rec_loss"
    embed_dim: 3
    lossconfig:
      target:  ldm.modules.losses.GaussianLoss
      params:
        kl_weight: 1.0e-6

    encoder:
      target: ldm.modules.diffusionmodules.model.Encoder
      params:
        double_z: True
        z_channels: 3
        resolution: 64
        in_channels: 1
        out_ch: 3
        ch: 32
        ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
        num_res_blocks: 2
        attn_resolutions: [ ]

    data_converter:
      target:  ldm.data.data_converters.conversion.ERA5Converter
      params:
        data_shape: [46,90]
        normalize_features: False

    decoder:
      target: ldm.modules.decoders.trans_inr.TransInr
      params:
        data_shape: [64,64]
        update_strategy: scale
        tokenizer:
          target: ldm.modules.decoders.tokenizers.latent_tokenizer.LatentTokenizer
          params:                 # z is (latent_dim, latent_size, latent_size)
            latent_dim: 3         # latent depth is doubled in post_quant_conv
            latent_size: [11,22]  
            patch_size: 1         # Produces 64 tokens (8x8 grid)
            n_head: 4             # 4 attention heads for better feature mixing
            head_dim: 32          # 32 per-head embedding size

        inr:
          target: ldm.modules.decoders.inrs.siren.SIREN
          params:
            in_dim: 3
            out_dim: 1
            out_bias: 0.5
            depth: 5
            hidden_dim: 256

            
        n_groups: 64
        transformer:
          target: ldm.modules.decoders.transformer.Transformer
          params:
            dim: 104
            encoder_depth: 4
            decoder_depth: 4
            n_head: 4
            head_dim: 26
            ff_dim: 416




data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 128
    num_workers: 8
    wrap: false
    train:
      target: ldm.data.era.ERA5Dataset
      params:
        path_to_data: /work3/ipeaz/data/era5/era5_temp2m_16x_train
    validation:
      target: ldm.data.era.ERA5Dataset
      params:
        path_to_data: /work3/ipeaz/data/era5/era5_temp2m_16x_val
    test:
      target: ldm.data.era.ERA5Dataset
      params:
        path_to_data: /work3/ipeaz/data/era5/era5_temp2m_16x_test


lightning:
  callbacks:
    image_logger:
      target: main.ERA5Logger
      params:
        disabled: True
        batch_frequency: 1000
        max_images: 4
        cols: 1
        increase_log_steps: True
        log_first_step: True
        logger_kwargs:
          super_resolution: False

  trainer:
    max_epochs: -1
    benchmark: True
