model:
  base_learning_rate: 1.0e-5
  target: ldm.models.autoencoder.IVQModel
  params:
    ckpt_path: 'model.ckpt.1'    # https://ommer-lab.com/files/latent-diffusion/nitro/cin/
    monitor: "val/rec_loss"
    embed_dim: 3
    n_embed: 8192
    lossconfig:
      target: ldm.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 1e6     
        disc_weight: 0.75
        codebook_weight: 1.0

    encoder:
      target: ldm.modules.diffusionmodules.model.Encoder
      params:
        double_z: false
        z_channels: 3
        resolution: 256
        in_channels: 3
        out_ch: 3
        ch: 128
        ch_mult:
        - 1
        - 2
        - 4
        num_res_blocks: 2
        attn_resolutions: []
        dropout: 0.0

    decoder:
      target: ldm.modules.decoders.trans_inr.TransInr
      params:
        data_shape: [256, 256]
        update_strategy: scale
        tokenizer:
          target: ldm.modules.decoders.tokenizers.latent_tokenizer.LatentTokenizer
          params:                 # z is (latent_dim, latent_size, latent_size)
            latent_dim: 3         # 3-channel latent tensor
            latent_size: 64       # 16 sized latent tensor  
            patch_size: 4         
            n_head: 4             # 4 attention heads for better feature mixing
            head_dim: 32          # 32 per-head embedding size

        inr:
          target: ldm.modules.decoders.inrs.siren.SIREN
          params:
            in_dim: 2
            out_dim: 3 
            out_bias: 0.5
            depth: 5 
            hidden_dim: 256
            
        n_groups: 128   # in Trans-INR CelebA: 64
        transformer:
          target: ldm.modules.decoders.transformer.Transformer
          params:
            dim: 768 
            encoder_depth: 6 
            decoder_depth: 6  
            n_head: 12 
            head_dim: 64 
            ff_dim: 3072  


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 8
    wrap: false
    train:
      target: ldm.data.imagenet.ImageNetTrain
      params:
        data_root: '/public/home/group_yangych/lulucai/data/imagenet/imagenet100'
    validation:
      target:  ldm.data.imagenet.ImageNetValidation
      params:
        data_root: '/public/home/group_yangych/lulucai/data/imagenet/imagenet100'


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 9
        increase_log_steps: False
        log_first_step: False

  trainer:
    max_epochs: -1  # Infinite epochs
    benchmark: True
